#!/bin/bash

# Install HAproxy
sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig # backup the original config file
sudo cat > /etc/haproxy/haproxy.cfg << EOF
frontend http-in
  bind *:80
  default_backend servers

backend servers
  balance roundrobin
  server web-01 97533-web-01:80 check
  server web-02 97533-web-02:80 check
EOF

# Make sure that HAproxy can be managed via an init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy
